# Generated by Django 5.1.3 on 2024-11-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('image', models.ImageField(default='images/default_FdKeTks.jpg', upload_to='images/')),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Photography', 'Photography'), ('Personal Projects', 'Personal Projects'), ('Bootcamp Projects', 'Bootcamp Projects'), ('Client Work', 'Client Work'), ('Open Source', 'Open Source'), ('Mobile Development', 'Mobile Development')], max_length=50)),
            ],
        ),
    ]
